.catalog:
  name: wise2c-ci
  version: "0.0.1"
  description: |
    Wise2c Continuous Integration Solution Platform
  questions:
    - variable: release_version
      label: "Wise2c CI Version"
      type: "string"
      required: true
      description: |
        Wise2c CI Version
    - variable: http_port
      label: "Web Public Http Port"
      type: "string"
      required: true
      description: |
        website public http port
    - variable: schedule_host_label
      label: "Schedule Host Label"
      required: true
      type: "string"
      description: |
        schedule host label
    - variable: schedule_host_label_value
      label: "Schedule Host Label Value"
      required: true
      type: "string"
      description: |
        schedule host label value
