.catalog:
  name: Wise2C-Registry
  version: v0.1
  description: |
    Wise2c Docker Registry
  maintainer: "Chen Leji <chenleji@wise2c.com>"
  questions:

    - variable: "VOLUME_DRIVER"
      label: "Shared Storage Volume Driver"
      description: "Shared storage volume driver."
      required: true
      default: "convoy-nfs"
      type: string

    - variable: "EXTERNAL_DIR"
      label: "Shared Storage Volume"
      description: "shared storage volume, which is used to sotrage configuration files.(You should copy your Cert & Key files to this volume under '/cert' forder, such as /cert/reg.wise2c.com.crt & /cert/reg.wise2c.com.key)."
      required: true
      default: "harbor"
      type: string

    - variable: "BACKEND_STORAGE_TYPE"
      label: "Backend Storage Type"
      description: "Backend storage type."
      required: true
      default: "SWIFT"
      type: enum
      options:
        - NAS
        - SWIFT

    - variable: "SWIFT_AUTH_URL"
      label: "Swift Authen URL"
      description: "Swift authen URL."
      default: ""
      type: string

    - variable: "SWIFT_USER_NAME"
      label: "Swift Authen User Name"
      description: "Swift authen user name."
      default: ""
      type: string

    - variable: "SWIFT_PASSWD"
      label: "Swift Authen Password"
      description: "Swift authen password."
      default: ""
      type: string

    - variable: "SWIFT_CONTAINER"
      label: "Swift Container"
      description: "Swift container which is used to storage images."
      default: ""
      type: string

    - variable: "HOSTNAME"
      label: "Hostname"
      description: "The target host's hostname, which is used to access the UI and the registry service."
      required: true
      default: "reg.wise2c.com"
      type: string

    - variable: "UI_URL_PROTOCOL"
      label: "URL Protocol"
      description: "The protocol used to access the UI and the token/notification service. By default, this is http. "
      required: true
      default: "https"
      type: enum
      options:
        - https
        - http

    - variable: "EMAIL_SERVER"
      label: "Email Server"
      description: "These parameters are needed for Harbor to be able to send a user a 'password reset' email."
      required: true
      default: "smtp.mydomain.com"
      type: string

    - variable: "EMAIL_SERVER_PORT"
      label: "Email Server Port"
      description: "Wise2C Registry Email Server Port"
      required: true
      default: 25
      type: int

    - variable: "EMAIL_USERNAME"
      label: "Email Username"
      description: "Wise2C Registry Email Username"
      required: true
      default: "sample_admin@mydomain.com"
      type: string


    - variable: "EMAIL_PASSWORD"
      label: "Email Password"
      description: "Wise2C Registry Email Password. The default password is abc"
      required: true
      default: "abc"
      type: password

    - variable: "EMAIL_FROM"
      label: "Wise2C Registry Email From"
      description: ""
      required: true
      default: "admin <sample_admin@mydomain.com>"
      type: string

    - variable: "EMAIL_SSL"
      label: "Wise2C Registry Email SSL"
      description: ""
      required: true
      default: true
      type: boolean

    - variable: "HARBOR_ADMIN_PASSWORD"
      label: "Wise2C Registry Admin Password"
      description: "The adminstrator's password. The default username/password are admin/Harbor12345."
      required: true
      default: "Harbor12345"
      type: password

    - variable: "AUTH_MODE"
      label: "Wise2C Registry Auth Mode"
      description: "The type of authenticationDB_PASSWORD that is used. "
      required: true
      default: "db_auth"
      type: enum
      options:
        - db_auth
        - ldap_auth

    - variable: "LDAP_URL"
      label: "Wise2C Registry LDAP URL"
      description: "The LDAP endpoint URL (e.g. ldaps://ldap.mydomain.com). Only used when auth_mode is set to ldap_auth ."
      default: "ldaps://ldap.mydomain.com"
      type: string

    - variable: "LDAP_BASEDN"
      label: "Wise2C Registry LDAP BaseDN"
      description: "The basedn template for verifying the user's credential against an LDAP (e.g. uid=%s,ou=people,dc=mydomain,dc=com ) or an AD (e.g. CN=%s,OU=Dept1,DC=mydomain,DC=com) server."
      default: "uid=%s,ou=people,dc=mydomain,dc=com"
      type: string

    - variable: "DB_PASSWORD"
      label: "Wise2C Registry DB Password"
      description: "The root password for the mySQL database used for db_auth. The default password is root123"
      required: true
      default: "root123"
      type: password

    - variable: "SELF_REGISTRATION"
      label: "Wise2C Registry Self Registration"
      description: "Enable / Disable the ability for a user to register themselves."
      required: true
      default: "on"
      type: enum
      options:
        - on
        - off

    - variable: "CUSTOMIZE_CRT"
      label: "Wise2C Registry Custromize CRT"
      description: "When this attribute is on, the prepare script creates private key and root certificate for the generation/verification of the regitry's token. "
      required: true
      default: "on"
      type: enum
      options:
        - on
        - off

    - variable: "CRT_COUNTRY"
      label: "Wise2C Registry CRT Country"
      description: ""
      default: "CN"
      type: string

    - variable: "CRT_STATE"
      label: "Wise2C Registry CRT State"
      description: ""
      default: "SC"
      type: string

    - variable: "CRT_LOCATION"
      label: "Wise2C Registry CRT Location"
      description: ""
      default: "CD"
      type: string

    - variable: "CRT_ORGANIZATION"
      label: "Wise2C Registry CRT Organization"
      description: ""
      default: "WISE2C"
      type: string

    - variable: "CRT_ORGANIZATIONALUNIT"
      label: "Wise2C Registry CRT Organization Unit"
      description: ""
      default: "DEVELOP"
      type: string

    - variable: "CRT_COMMONNAME"
      label: "Wise2C Registry CRT Common Name"
      description: ""
      default: "reg.wise2c.com"
      type: string

    - variable: "CRT_EMAIL"
      label: "Wise2C Registry CRT Email"
      description: ""
      default: ""
      type: string

    - variable: "MAX_JOB_WORKERS"
      label: "Wise2C Registry MAX Job Workers"
      description: "The maximum number of replication workers in job service. "
      required: true
      default: 3
      type: int

    - variable: "VERIFY_REMOTE_CERT"
      label: "Wise2C Registry Verify Rmote CRT"
      description: "This flag determines whether or not to verify SSL/TLS certificate when Harbor communicates with a remote registry instance."
      required: true
      default: "on"
      type: enum
      options:
        - on
        - off

prepare:
  scale: 1
#log:
#  scale: 1
registry:
  scale: 1
mysql:
  scale: 1
ui:
  scale: 1
jobservice:
  scale: 1
